### ISSUE TITLE
IOS: the fileSize of the selected image is bigger then the original one [🐛] 

### ISSUE THREAD

**Issue by likashefqet** [react-native-image-picker/react-native-image-picker#1894] opened 2021-12-15 16:11 UTC
### Description

Continues to happen in version 4.

After selecting an image using the library, the asset object contains a fileSize that is different (bigger) from the original image size.
NO maxWidth and NO maxHeight were applied. quality: 1.

This issue has been reported a couple of times in the past [#1419](https://github.com/react-native-image-picker/react-native-image-picker/issues/1419), [#514](https://github.com/react-native-image-picker/react-native-image-picker/issues/514) but these reports have been closed and the issue continues to happen.

### How to repeat issue and example

- Note the image size from the photos app on iOS
- Select that image using this library (NO maxWidth, NO maxHeight, quality: 1) and compare the sizes (sometimes the image is 2 or even 3 times bigger in size)

![IMG_0327](https://user-images.githubusercontent.com/22661589/146235492-e42c7f13-4241-4515-828c-9e51272a3606.jpg)

```javascript
launchImageLibrary({
  includeBase64: false,
  mediaType: 'photo',
  quality: 1,
  selectionLimit: 1,
}, (response) => {
  const { assets } = response;

  if (Array.isArray(assets) && assets.length > 0) {
    const [{ fileSize }] = assets;

    console.log(fileSize / 1024 / 1024);
    console.log(fileSize / 1000 / 1000);
  }
})
```
Expected: 1.9
Result: 
```
6.392001152038574
6.7024989999999995
```

### Solution

What needs to be done to address this issue?

Make sure that the fileSize of the selected image is the same as the original one when no maxWidth and no maxHeight options provided and quality option is set at 1.

### Additional Information
Tested on:
- Image Picker version: v4.1.1 and v4.6.0
- React Native version: v0.63.3
- Platform: iOS (iPhone 11 - real device)
- Development Operating System: MacOS v12.0 and v12.1
- Dev tools:
    - Xcode v13.1 and v13.2
    - iOS v14.4, v15.1 and v15.2
    - node v14.17.4

**Comment by LefterisL** [comment] 2021-12-17 17:23
Indeed I came up on this myself too. On Android the filesize is reduced just fine but on iOS I once noticed an image from 1.7MB to become 3MB.

**Comment by christianrank** [comment] 2022-01-27 11:40
iOS stores images internally in High Efficiency Image File Format (.heif / .heic) and converts it to .jpg when it is selected. So it is correct that it gets bigger with quality 1, because jpeg is less efficient.

To get a smaller file size, you have to adjust the quality option.

**Comment by shefqet-lika** [comment] 2022-02-04 13:26
@christianrank When shared via AirDrop or other apps, the same image is converted to .jpg and the size is still way smaller
Tried to share the same image (details attached)
- via AirDrop to a MAC laptop and the size shows as 3.8MB
- via WeTransfer to an Android phone and the size shows as 3.8MB

While picking the image with this library makes it a 6.3MB

<img width="668" alt="Screenshot 2022-02-04 at 2 20 50 PM" src="https://user-images.githubusercontent.com/83773114/152536557-65737845-af19-44d7-9578-b3daf45aa122.png">

**Comment by likashefqet** [comment] 2022-02-04 13:27
@christianrank When shared via AirDrop or other apps, the same image is converted to .jpg and the size is still way smaller
Tried to share the same image (details attached)

- via AirDrop to a MAC laptop and the size shows as 3.8MB
- via WeTransfer to an Android phone and the size shows as 3.8MB

While picking the image with this library makes it a 6.3MB

<img width="668" alt="Screenshot 2022-02-04 at 2 20 50 PM" src="https://user-images.githubusercontent.com/22661589/152536844-11bc7f1e-6224-40e7-84a9-274074a73a51.png">

**Comment by ankhuve** [comment] 2022-03-24 08:29
We're experiencing the same thing with iOS. The `quality` option doesn't affect the final file size either.

**Comment by ntdiary** [comment] 2022-07-17 13:33
Hi
in my test, png file size also increased.
The root cause is here
although we only want to pick the image original data,
`UIImageJPEGRepresentation ` or `UIImagePNGRepresentation` always change the image binary data to achieve some optimization result (It is only related to the internal implementation of IOS, not to `quality`).
https://github.com/react-native-image-picker/react-native-image-picker/blob/eeca93864d9ea671a2e268f36936aafeab90cfe1/ios/ImagePickerManager.m#L134-L138

Can we add an option to avoid this change?
If possible, I can submit a PR 🙂

**Comment by ntdiary** [comment] 2022-07-20 11:03
a temporary solution:
try to patch the `ImagePickerManager.m` file
and no `maxWidth`, no `maxHeight`, `quality` is 1 (default value).
In this way, the selected file will be close to the original file size (their binary data is different).
If any questions, please give me feedback 🙂
```diff
diff --git a/ios/ImagePickerManager.m b/ios/ImagePickerManager.m
index f311a98..8e8c99c 100644
--- a/ios/ImagePickerManager.m
+++ b/ios/ImagePickerManager.m
@@ -121,20 +121,32 @@ RCT_EXPORT_METHOD(launchImageLibrary:(NSDictionary *)options callback:(RCTRespon
 -(NSMutableDictionary *)mapImageToAsset:(UIImage *)image data:(NSData *)data phAsset:(PHAsset * _Nullable)phAsset {
     NSString *fileType = [ImagePickerUtils getFileType:data];

-    if ((target == camera) && [self.options[@"saveToPhotos"] boolValue]) {
+    if (target == camera) {
+        if ([self.options[@"saveToPhotos"] boolValue]) {
             UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil);
         }
+        CFMutableDataRef imageData = CFDataCreateMutable(NULL, 0);
+        CGImageDestinationRef destination = CGImageDestinationCreateWithData(imageData, kUTTypeJPEG, 1, NULL);
+        CGImageDestinationAddImage(destination, image.CGImage, NULL);
+        CGImageDestinationFinalize(destination);
+        CFRelease(destination);
+        data = (__bridge NSData *)imageData;
+    }

+    UIImage* newImage = image;
     if (![fileType isEqualToString:@"gif"]) {
-        image = [ImagePickerUtils resizeImage:image
+        newImage = [ImagePickerUtils resizeImage:image
                                      maxWidth:[self.options[@"maxWidth"] floatValue]
                                     maxHeight:[self.options[@"maxHeight"] floatValue]];
     }

+    float quality = [self.options[@"quality"] floatValue];
+    if (![image isEqual:newImage] || (quality >= 0 && quality < 1)) {
         if ([fileType isEqualToString:@"jpg"]) {
-        data = UIImageJPEGRepresentation(image, [self.options[@"quality"] floatValue]);
+            data = UIImageJPEGRepresentation(newImage, quality);
         } else if ([fileType isEqualToString:@"png"]) {
-        data = UIImagePNGRepresentation(image);
+            data = UIImagePNGRepresentation(newImage);
+        }
     }

     NSMutableDictionary *asset = [[NSMutableDictionary alloc] init];
@@ -159,8 +171,8 @@ RCT_EXPORT_METHOD(launchImageLibrary:(NSDictionary *)options callback:(RCTRespon
     }

     asset[@"fileName"] = fileName;
-    asset[@"width"] = @(image.size.width);
-    asset[@"height"] = @(image.size.height);
+    asset[@"width"] = @(newImage.size.width);
+    asset[@"height"] = @(newImage.size.height);

     if(phAsset){
         asset[@"timestamp"] = [self getDateTimeInUTC:phAsset.creationDate];
```
<img src="https://user-images.githubusercontent.com/8579651/179965380-2e047546-3563-4a08-bf6d-8717cb481b34.png"  width="500px" />
this test is for `launchCamera `, the size difference may be smaller for `launchImageLibrary `.

**Comment by ntdiary** [comment] 2022-07-21 10:54
In addition
if the above temp image size is still larger when transferring over the network,
it's likely because the `RCTNetworking.mm` is still using `RCTImageLoader.mm` to convert the image uri to binary data.
and you can customize a new handler to the `RCTNetworking.mm` (put these two files in your project)
```objective-c
//
//  OriginImageRequestHandler.h
//

#import <React/RCTURLRequestHandler.h>

@interface OriginImageRequestHandler : NSObject <RCTURLRequestHandler>

@end

```

```objective-c
//
//  OriginImageRequestHandler.mm
//

#import <Foundation/Foundation.h>
#import <ReactCommon/RCTTurboModule.h>

#import <MobileCoreServices/MobileCoreServices.h>
#import <React/RCTUtils.h>

#import "OriginImageRequestHandler.h"

@interface OriginImageRequestHandler() <RCTTurboModule>

@end

@implementation OriginImageRequestHandler
{
  NSOperationQueue *_fileQueue;
}

RCT_EXPORT_MODULE()

- (void)invalidate
{
  [_fileQueue cancelAllOperations];
  _fileQueue = nil;
}

- (BOOL)canHandleRequest:(NSURLRequest *)request
{
  NSLog(@"home path is %@", NSHomeDirectory());
  return [request.URL.scheme caseInsensitiveCompare:@"file"] == NSOrderedSame
  && RCTIsLocalAssetURL(request.URL)
  && !RCTIsBundleAssetURL(request.URL);
}

- (NSOperation *)sendRequest:(NSURLRequest *)request
                withDelegate:(id<RCTURLRequestDelegate>)delegate
{
  // Lazy setup
  if (!_fileQueue) {
    _fileQueue = [NSOperationQueue new];
    _fileQueue.maxConcurrentOperationCount = 4;
  }

  __weak __block NSBlockOperation *weakOp;
  __block NSBlockOperation *op = [NSBlockOperation blockOperationWithBlock:^{

    // Get content length
    NSError *error = nil;
    NSFileManager *fileManager = [NSFileManager new];
    NSDictionary<NSString *, id> *fileAttributes = [fileManager attributesOfItemAtPath:request.URL.path error:&error];
    if (!fileAttributes) {
      [delegate URLRequest:weakOp didCompleteWithError:error];
      return;
    }

    // Get mime type
    NSString *fileExtension = [request.URL pathExtension];
    NSString *UTI = (__bridge_transfer NSString *)UTTypeCreatePreferredIdentifierForTag(
      kUTTagClassFilenameExtension, (__bridge CFStringRef)fileExtension, NULL);
    NSString *contentType = (__bridge_transfer NSString *)UTTypeCopyPreferredTagWithClass(
      (__bridge CFStringRef)UTI, kUTTagClassMIMEType);

    // Send response
    NSURLResponse *response = [[NSURLResponse alloc] initWithURL:request.URL
                                                        MIMEType:contentType
                                           expectedContentLength:[fileAttributes[NSFileSize] ?: @-1 integerValue]
                                                textEncodingName:nil];

    [delegate URLRequest:weakOp didReceiveResponse:response];

    // Load data
    NSData *data = [NSData dataWithContentsOfURL:request.URL
                                         options:NSDataReadingMappedIfSafe
                                           error:&error];
    if (data) {
      [delegate URLRequest:weakOp didReceiveData:data];
    }
    [delegate URLRequest:weakOp didCompleteWithError:error];
  }];

  weakOp = op;
  [_fileQueue addOperation:op];
  return op;
}

- (void)cancelRequest:(NSOperation *)op
{
  [op cancel];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
  return nullptr;
}

- (float)handlerPriority
{
  return 4;
}

@end

Class OriginImageRequestHandlerCls(void) {
  return OriginImageRequestHandler.class;
}

```

**Closed** 2022-10-31 12:41 UTC
Labels: :bug: Bug
