### ISSUE TITLE
in open camera when we press close i.e. cross icon app gets crash[🐛] 

### ISSUE THREAD

**Issue by al0kdash** [react-native-image-picker/react-native-image-picker#1522] opened 2020-12-10 11:11 UTC
### Description

Explain the bug in as much detail as possible

### How to repeat issue and example

- step to reproduce the issue
- ...

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- React Native version: [FILL THIS OUT: Be specific, filling out "latest" here is not enough.]
- Platform: [FILL THIS OUT: iOS, Android, or both?]
- Development Operating System: [FILL THIS OUT: Are you developing on MacOS, Linux, or Windows?]
- Dev tools: [FILL THIS OUT: Xcode or Android Studio version, iOS or Android SDK version, if applicable] navigation crash for Android

**Comment by ravirajn22** [comment] 2020-12-10 11:42
See android Logcat for error and post it here. Without that we cannot diagnose.  And spend some time and fill the details first.

**Comment by ravirajn22** [comment] 2020-12-10 16:02
Duplicate of https://github.com/react-native-image-picker/react-native-image-picker/issues/1521

**Closed by ravirajn22** 2020-12-10 16:02 UTC
Labels: :bug: Bug
