### ISSUE TITLE
[🐛] Media type 'mixed' is removed on ver3?

### ISSUE THREAD

**Issue by 15110011** [react-native-image-picker/react-native-image-picker#1544] opened 2020-12-17 04:55 UTC
### Description
I'm using ver 3 and I saw type 'mixed' is no longer on this version.
How can I pick both photos and videos? Any help?

**Comment by ravirajn22** [comment] 2020-12-17 06:13
duplicate of #1527

**Closed by ravirajn22** 2020-12-17 06:13 UTC
Labels: :bug: Bug

**Comment by 15110011** [comment] 2020-12-17 06:34
oh, I see. Thank you. So now if I want to use this type I have to install version 2?
