### ISSUE TITLE
GPS Information that included in selected file

### ISSUE THREAD

**Issue by jvence** [react-native-image-picker/react-native-image-picker#1626] opened 2021-02-24 20:19 UTC
When I upload an image from Safari to the server from a React JS app using fetch, it extract GPS information correctly, however if the same photo is uploaded using react-native-image-picker and fetch (from a react native app), the GPS information is never passed to the server. Using   "react-native-image-picker": "^3.2.1",

Try both with noData: false & noData: true:

`		const options = {
			noData: false,
		};
		ImagePicker.launchImageLibrary(options, (response) => {
			console.log('response.uri=' + response.uri);
			if (response.uri) {
				setCurrentFile(response);
			}
		});`

Does anyone know what is happening?

**Comment by jvence** [comment] 2021-02-24 20:35
Tried with launchCamera and had the same issue

**Comment by chanoo** [comment] 2021-03-09 06:24
not perfectly
only launchImageLibrary working..

```
#import "ImagePickerManager.h"
#import "ImagePickerUtils.h"
#import <React/RCTConvert.h>
#import <AVFoundation/AVFoundation.h>
#import <Photos/Photos.h>
#import <PhotosUI/PhotosUI.h>
#import <React/RCTUtils.h>

@import MobileCoreServices;

API_AVAILABLE(ios(14))
@interface ImagePickerManager ()

@property (nonatomic, strong) UIImagePickerController *picker;
@property (nonatomic, strong) PHPickerViewController *phpicker;
@property (nonatomic, strong) RCTResponseSenderBlock callback;
@property (nonatomic, retain) NSDictionary *options;
@property (nonatomic, retain) NSMutableDictionary *response;

@end

@implementation ImagePickerManager

NSString *errCameraUnavailable = @"camera_unavailable";
NSString *errPermission = @"permission";
NSString *errOthers = @"others";
RNImagePickerTarget target;

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(launchCamera:(NSDictionary *)options callback:(RCTResponseSenderBlock)callback)
{
    target = camera;
    dispatch_async(dispatch_get_main_queue(), ^{
        [self launchImagePicker:options callback:callback];
    });
}

RCT_EXPORT_METHOD(launchImageLibrary:(NSDictionary *)options callback:(RCTResponseSenderBlock)callback)
{
    target = library;
    dispatch_async(dispatch_get_main_queue(), ^{
        [self launchImagePicker:options callback:callback];
    });
}

- (void)launchImagePicker:(NSDictionary *)options callback:(RCTResponseSenderBlock)callback
{
    self.options = options;
    self.callback = callback;

    if (@available(iOS 14, *)) {
        PHPickerConfiguration *configuration = [[PHPickerConfiguration alloc] init];
        configuration.selectionLimit = 1;
        configuration.filter = [PHPickerFilter imagesFilter];

        self.phpicker = [[PHPickerViewController alloc] initWithConfiguration:configuration];
        self.phpicker.delegate = self;

        [self checkPermission:^(BOOL granted) {
            if (!granted) {
                self.callback(@[@{@"errorCode": errPermission}]);
                return;
            }
            [self showPickerViewController];
        }];
        
    } else {
        
        if (target == camera && [ImagePickerUtils isSimulator]) {
            self.callback(@[@{@"errorCode": errCameraUnavailable}]);
            return;
        }
        
        self.picker = [[UIImagePickerController alloc] init];
        
        [ImagePickerUtils setupPickerFromOptions:self.picker options:self.options target:target];
        self.picker.delegate = self;
        [self checkPermission:^(BOOL granted) {
            if (!granted) {
                self.callback(@[@{@"errorCode": errPermission}]);
                return;
            }
            [self showPickerViewController];
        }];
    }
    
}

-(void)picker:(PHPickerViewController *)picker didFinishPicking:(NSArray<PHPickerResult *> *)results API_AVAILABLE(ios(14)) API_AVAILABLE(ios(14)){

    NSItemProvider *itemProvider = results.firstObject.itemProvider;
    
    dispatch_block_t dismissCompletionBlock = ^{
        if ([itemProvider canLoadObjectOfClass:[UIImage class]]) {
            [self onImage2Obtained:results];
        }
    };

    [picker dismissViewControllerAnimated:YES completion:dismissCompletionBlock];
}

- (void) showPickerViewController {
    
    dispatch_async(dispatch_get_main_queue(), ^{
        UIViewController *root = RCTPresentedViewController();
        if (@available(iOS 14, *)) {
            [root presentViewController:self.phpicker animated:YES completion:nil];
        } else {
            [root presentViewController:self.picker animated:YES completion:nil];
        }
    });

}

- (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *,id> *)info
{
    dispatch_block_t dismissCompletionBlock = ^{
        
        if ([[info objectForKey:UIImagePickerControllerMediaType] isEqualToString: (NSString *)kUTTypeImage]) {
            [self onImageObtained:info];
        } else {
            [self onVideoObtained:info];
        }
    };

    dispatch_async(dispatch_get_main_queue(), ^{
        [picker dismissViewControllerAnimated:YES completion:dismissCompletionBlock];
    });
}

- (void)imagePickerControllerDidCancel:(UIImagePickerController *)picker
{
    dispatch_async(dispatch_get_main_queue(), ^{
        [picker dismissViewControllerAnimated:YES completion:^{
            self.callback(@[@{@"didCancel": @YES}]);
        }];
    });
}

- (void)onImage2Obtained:(NSArray<PHPickerResult *> *) info  API_AVAILABLE(ios(14)){
    
    __block UIImage *image = nil;
    self.response = [[NSMutableDictionary alloc] init];

    int i = 0;
    for (PHPickerResult *result in info)
    {
        NSLog(@"PHPickerResult: %d", i);

        // Get UIImage
        [result.itemProvider loadObjectOfClass:[UIImage class] completionHandler:^(__kindof id<NSItemProviderReading>  _Nullable object, NSError * _Nullable error) {
            NSLog(@"object: %@, error: %@", object, error);

            if ([object isKindOfClass:[UIImage class]]) {
                image = (UIImage*)object;
            }
        }];
        
        while (image == nil) {
            NSLog(@"waiting...");
            [NSThread sleepForTimeInterval:10];
        }
        
        // Get UIImage
        [result.itemProvider loadItemForTypeIdentifier:(NSString *)kUTTypeImage options:nil completionHandler:^(id item, NSError *error) {
            
            if ([item isKindOfClass:[NSURL class]]) {
                NSURL *imageURL = item;
                
                NSError *error = nil;
                NSData *data = [NSData dataWithContentsOfURL:imageURL options:NSDataReadingUncached error:&error];
                
                CGImageSourceRef mySourceRef = CGImageSourceCreateWithData((CFDataRef)data, NULL);
                NSDictionary *exif = (__bridge NSDictionary *)CGImageSourceCopyPropertiesAtIndex(mySourceRef,0,NULL);
                NSLog(@"onImage2Obtained Picker ############# EXIF: %@", exif);
                self.response[@"exif"] = [[NSDictionary alloc] initWithDictionary:exif];
                
                if ((target == camera) && [self.options[@"saveToPhotos"] boolValue]) {
                    UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil);
                }

                self.response[@"width"] = @(image.size.width);
                self.response[@"height"] = @(image.size.height);
                NSLog(@"url: %@", data);
                NSLog(@"error: %@", error);

                NSString *fileType = [ImagePickerUtils getFileType:data];
                
                if (![fileType isEqualToString:@"gif"]) {
                    image = [ImagePickerUtils resizeImage:image maxWidth:[self.options[@"maxWidth"] floatValue] maxHeight:[self.options[@"maxHeight"] floatValue]];
                }

//                if ([fileType isEqualToString:(NSString *)@"jpg"]) {
//                    data = UIImageJPEGRepresentation(image, [self.options[@"quality"] floatValue]);
//                } else if ([fileType isEqualToString:(NSString *)@"png"]) {
//                    data = UIImagePNGRepresentation(image);
//                } else {
//                    data = [NSData dataWithContentsOfURL:imageURL];
//                }
                
                self.response[@"type"] = [@"image/" stringByAppendingString:fileType];
            
                NSString *fileName = [self getImageFileName:fileType];
                NSString *path = [[NSTemporaryDirectory() stringByStandardizingPath] stringByAppendingPathComponent:fileName];
                [data writeToFile:path atomically:YES];
            
                if ([self.options[@"includeBase64"] boolValue]) {
                    self.response[@"base64"] = [data base64EncodedStringWithOptions:0];
                }
            
                NSURL *fileURL = [NSURL fileURLWithPath:path];
                self.response[@"uri"] = [fileURL absoluteString];
                
                NSNumber *fileSizeValue = nil;
                NSError *fileSizeError = nil;
                [fileURL getResourceValue:&fileSizeValue forKey:NSURLFileSizeKey error:&fileSizeError];
                if (fileSizeValue){
                    self.response[@"fileSize"] = fileSizeValue;
                }

                self.response[@"fileName"] = fileName;
                
                NSLog(@"self.response 1: %@", self.response);
                self.callback(@[self.response]);
            }

        }];

    }

}

- (void)onImageObtained:(NSDictionary<NSString *,id> *)info {

    NSURL *imageURL = [ImagePickerManager getNSURLFromInfo:info];
    self.response = [[NSMutableDictionary alloc] init];
    UIImage *image = [ImagePickerManager getUIImageFromInfo:info];
    NSData *data;

    if ((target == camera) && [self.options[@"saveToPhotos"] boolValue]) {
        UIImageWriteToSavedPhotosAlbum(image, nil, nil, nil);
    }

    NSString *fileType = [ImagePickerUtils getFileType:[NSData dataWithContentsOfURL:imageURL]];
    
    if (![fileType isEqualToString:@"gif"]) {
        image = [ImagePickerUtils resizeImage:image maxWidth:[self.options[@"maxWidth"] floatValue] maxHeight:[self.options[@"maxHeight"] floatValue]];
    }
    
    if ([fileType isEqualToString:(NSString *)@"jpg"]) {
        data = UIImageJPEGRepresentation(image, [self.options[@"quality"] floatValue]);
    } else if ([fileType isEqualToString:(NSString *)@"png"]) {
        data = UIImagePNGRepresentation(image);
    } else {
        data = [NSData dataWithContentsOfURL:imageURL];
    }
    
    CGImageSourceRef mySourceRef = CGImageSourceCreateWithData((CFDataRef)data, NULL);
    if (mySourceRef != NULL)
    {
        NSDictionary *exif = (__bridge NSDictionary *)CGImageSourceCopyPropertiesAtIndex(mySourceRef,0,NULL);
        NSLog(@"Image Picker ############# EXIF: %@", exif);
    }

    self.response[@"type"] = [@"image/" stringByAppendingString:fileType];

    NSString *fileName = [self getImageFileName:fileType];
    NSString *path = [[NSTemporaryDirectory() stringByStandardizingPath] stringByAppendingPathComponent:fileName];
    [data writeToFile:path atomically:YES];

    if ([self.options[@"includeBase64"] boolValue]) {
        self.response[@"base64"] = [data base64EncodedStringWithOptions:0];
    }

    NSURL *fileURL = [NSURL fileURLWithPath:path];
    self.response[@"uri"] = [fileURL absoluteString];

    NSNumber *fileSizeValue = nil;
    NSError *fileSizeError = nil;
    [fileURL getResourceValue:&fileSizeValue forKey:NSURLFileSizeKey error:&fileSizeError];
    if (fileSizeValue){
        self.response[@"fileSize"] = fileSizeValue;
    }

    self.response[@"fileName"] = fileName;
    self.response[@"width"] = @(image.size.width);
    self.response[@"height"] = @(image.size.height);

    NSLog(@"self.response 2: %@", self.response);
    self.callback(@[self.response]);
    
}

- (void)onVideoObtained:(NSDictionary<NSString *,id> *)info {
    NSString *fileName = [info[UIImagePickerControllerMediaURL] lastPathComponent];
    NSString *path = [[NSTemporaryDirectory() stringByStandardizingPath] stringByAppendingPathComponent:fileName];

    self.response = [[NSMutableDictionary alloc] init];
    
    NSURL *videoURL = info[UIImagePickerControllerMediaURL];
    NSURL *videoDestinationURL = [NSURL fileURLWithPath:path];

    if ((target == camera) && [self.options[@"saveToPhotos"] boolValue]) {
        UISaveVideoAtPathToSavedPhotosAlbum(videoURL.path, nil, nil, nil);
    }

    if ([videoURL.URLByResolvingSymlinksInPath.path isEqualToString:videoDestinationURL.URLByResolvingSymlinksInPath.path] == NO) {
        NSFileManager *fileManager = [NSFileManager defaultManager];

        // Delete file if it already exists
        if ([fileManager fileExistsAtPath:videoDestinationURL.path]) {
            [fileManager removeItemAtURL:videoDestinationURL error:nil];
        }

        if (videoURL) { // Protect against reported crash
          NSError *error = nil;

          // If we have write access to the source file, move it. Otherwise use copy.
          if ([fileManager isWritableFileAtPath:[videoURL path]]) {
            [fileManager moveItemAtURL:videoURL toURL:videoDestinationURL error:&error];
          } else {
            [fileManager copyItemAtURL:videoURL toURL:videoDestinationURL error:&error];
          }

          if (error) {
              self.callback(@[@{@"errorCode": errOthers, @"errorMessage":  error.localizedFailureReason}]);
              return;
          }
        }
    }

    self.response[@"uri"] = videoDestinationURL.absoluteString;
    self.callback(@[self.response]);
}

#pragma mark - Helpers

- (void)checkCameraPermissions:(void(^)(BOOL granted))callback
{
    AVAuthorizationStatus status = [AVCaptureDevice authorizationStatusForMediaType:AVMediaTypeVideo];
    if (status == AVAuthorizationStatusAuthorized) {
        callback(YES);
        return;
    } else if (status == AVAuthorizationStatusNotDetermined){
        [AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL granted) {
            callback(granted);
            return;
        }];
    } else {
        callback(NO);
    }
}

- (void)checkPhotosPermissions:(void(^)(BOOL granted))callback
{
    PHAuthorizationStatus status = [PHPhotoLibrary authorizationStatus];
    if (status == PHAuthorizationStatusAuthorized) {
        callback(YES);
        return;
    } else if (status == PHAuthorizationStatusNotDetermined) {
        [PHPhotoLibrary requestAuthorization:^(PHAuthorizationStatus status) {
            if (status == PHAuthorizationStatusAuthorized) {
                callback(YES);
                return;
            }
            else {
                callback(NO);
                return;
            }
        }];
    }
    else {
        callback(NO);
    }
}

// Both camera and photo write permission is required to take picture/video and store it to public photos
- (void)checkCameraAndPhotoPermission:(void(^)(BOOL granted))callback {

    [self checkCameraPermissions:^(BOOL cameraGranted) {
        if (!cameraGranted) {
            callback(NO);
            return;
        }

        [self checkPhotosPermissions:^(BOOL photoGranted) {
            if (!photoGranted) {
                callback(NO);
                return;
            }
            callback(YES);
        }];
    }];
}

- (void)checkPermission:(void(^)(BOOL granted)) callback {

    void (^permissionBlock)(BOOL) = ^(BOOL permissionGranted) {
        if (!permissionGranted) {
            callback(NO);
            return;
        }
        callback(YES);
    };

    if (target == camera && [self.options[@"saveToPhotos"] boolValue]) {
        [self checkCameraAndPhotoPermission:permissionBlock];
    }
    else if (target == camera) {
        [self checkCameraPermissions:permissionBlock];
    }
    else {
        if (@available(iOS 11.0, *)) {
            callback(YES);
        } else {
            [self checkPhotosPermissions:permissionBlock];
        }
    }
}

- (NSString*) getImageFileName:(NSString*)fileType {
    NSString *fileName = [[NSUUID UUID] UUIDString];
    fileName = [fileName stringByAppendingString:@"."];
    return [fileName stringByAppendingString:fileType];
}

+ (UIImage*)getUIImageFromInfo:(NSDictionary*)info {
    UIImage *image = info[UIImagePickerControllerEditedImage];
    if (!image) {
        image = info[UIImagePickerControllerOriginalImage];
    }
    return image;
}

+ (NSURL*)getNSURLFromInfo:(NSDictionary*)info {
    if (@available(iOS 11.0, *)) {
        return info[UIImagePickerControllerImageURL];
    } else {
        return info[UIImagePickerControllerReferenceURL];
    }
}
@end
```

**Comment by jvence** [comment] 2021-03-09 06:33
I'm using https://github.com/ivpusic/react-native-image-crop-picker with much better results

**Comment by ravirajn22** [comment] 2021-03-18 13:44
Duplicate of #1628

**Closed by ravirajn22** 2021-03-18 13:44 UTC
Labels: :bug: Bug
