### ISSUE TITLE
Couldn't get file path for photo on ANDROID 10 EMU

### ISSUE THREAD

**Issue by MOwais** [react-native-image-picker/react-native-image-picker#1350] opened 2020-04-23 19:41 UTC
# Bug

Camera doesn't open after granting permission and selecting Take Photo from popup.

Previously I was using version 1.1.0 on Android 9 without issue. After upgrading to Android 10 I started getting this error. Issue [1269 ](https://github.com/react-native-community/react-native-image-picker/issues/1269)is confirming the latest build v2.3.1 fixes this issue but after upgrading to 2.3.1 I am still getting the same error. This is on an Android 10 emulator.

`react-native info` output:

System:
    OS: Windows 10 10.0.17134
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 2.49 GB / 15.80 GB
  Binaries:
    Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.5 => 0.61.

Library version: ^2.3.1

Buildscript:

```
ext {
        buildToolsVersion =  "29.0.2"
        minSdkVersion = 16
        supportLibVersion = "29.0.0"
        compileSdkVersion = 29
        targetSdkVersion = 29
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.2")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

Usage:

    
```
         ImagePicker.showImagePicker(options, async (response) => {
                if (response.didCancel) {
                    console.log('User cancelled image picker');
                } else if (response.error) {
                    console.log('ImagePicker Error: ', response.error);
                    console.log(response);
                } else if (response.customButton) {
                    console.log('User tapped custom button: ', response.customButton);
                } else {
                    const source = { uri: response.uri };
                }
            });
        
        } 
   
   //ImagePicker Error:  Couldn't get file path for photo

```

The workaround in [1269 ](https://github.com/react-native-community/react-native-image-picker/issues/1269)asking for permission did not work either. I still log the same error.
 ```
      const granted = await PermissionsAndroid.request(
            PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
            {
            title: 'We need your permission'
            },
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
            console.log('You can use the camera');
        
            ImagePicker.showImagePicker(options, async (response) => {
                if (response.didCancel) {
                    console.log('User cancelled image picker');
                } else if (response.error) {
                    console.log('ImagePicker Error: ', response.error);
                    console.log(response);
                } else if (response.customButton) {
                    console.log('User tapped custom button: ', response.customButton);
                } else {
                    const source = { uri: response.uri };
                }
            });
        
        } 
        else {
            console.log('Camera permission denied');
        }
```
Did I miss a step here?

**Comment by Muzzamil75** [comment] 2020-04-24 13:09
Have you tried giving permission of external storage as well explicitly ?? @MOwais

**Comment by MOwais** [comment] 2020-04-24 13:27
> Have you tried giving permission of external storage as well explicitly ?? @MOwais
Is that not what the workaround is doing?

**Comment by Muzzamil75** [comment] 2020-04-24 13:46
Having the same issue in Android 10/ API 29..

**Comment by jaymdq** [comment] 2020-04-24 14:53
Having the same issue in Android 10!

**Comment by eespaillat** [comment] 2020-04-27 13:17
I was able to apply a short term fix to get this going added `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file.

I believe this is due to Android 10 scoped storage privacy changes and will require updating the library and how it reads/writes from the filesystem. My android dev experience is very limited but will submit a PR if I am able to figure it out.

**Comment by maomeiqi** [comment] 2020-04-28 06:56
Having the same issue in Android 10!

**Comment by zjz1993** [comment] 2020-04-29 07:49
+1, help!

**Comment by ahmetbicer** [comment] 2020-05-01 11:16
+1, I also got a log from adb logcat it says Invalid column latitude and app closes.

`Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/24/ORIGINAL/NONE/1788738914 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F24/ORIGINAL/NONE/1788738914} }} to activity {com.<packagename>/com.<packagename>.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude`

**Comment by chj-damon** [comment] 2020-05-06 07:18
> I was able to apply a short term fix to get this going by adding `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file.
> 
> I believe this is due to Android 10 scoped storage privacy changes and will require updating the library and how it reads/writes from the filesystem. My android dev experience is very limited but will submit a PR if I am able to figure it out.

Thanks, it works for me.

**Comment by ChameeraFortuna** [comment] 2020-05-21 08:29
> I was able to apply a short term fix to get this going by adding `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file.
> 
> I believe this is due to Android 10 scoped storage privacy changes and will require updating the library and how it reads/writes from the filesystem. My android dev experience is very limited but will submit a PR if I am able to figure it out.

This didn't work for me

**Comment by MattAgn** [comment] 2020-05-22 10:37
> I was able to apply a short term fix to get this going by adding `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file.
> 
> I believe this is due to Android 10 scoped storage privacy changes and will require updating the library and how it reads/writes from the filesystem. My android dev experience is very limited but will submit a PR if I am able to figure it out.

It worked for me as well! Thanks a lot!

**Comment by paulmasters** [comment] 2020-05-28 13:21
> I was able to apply a short term fix to get this going by adding `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file.
> 
> I believe this is due to Android 10 scoped storage privacy changes and will require updating the library and how it reads/writes from the filesystem. My android dev experience is very limited but will submit a PR if I am able to figure it out.

This is only a short term fix, what's the long term approach?

**Comment by PhilippNowak96** [comment] 2020-06-05 12:57
`requestLegacyExternalStorage` will be ignored as soon as you choose targetSdk 30. See: https://developer.android.com/preview/privacy/storage

```
To give developers additional time for testing, apps that target Android 10 (API level 29) can still request the requestLegacyExternalStorage attribute. This flag allows apps to temporarily opt out of the changes associated with scoped storage, such as granting access to different directories and different types of media files. After you update your app to target Android 11, the system ignores the requestLegacyExternalStorage flag.
```

So as @paulmasters asked, we need a long term fix for this.

**Comment by tophernuts** [comment] 2020-07-02 17:51
We also have this issue on Android 10!
The `requestLegacyExternalStorage` fix does solve the problem, but definitely is just a temporary fix, but with Android 11 beta coming out this month, we probably need a more definite fix!
![image](https://user-images.githubusercontent.com/4359781/86393372-32962280-bc5a-11ea-84dc-cd4f944ad6da.png)

Has anyone started investigating what the fix would entail or started on it!

**Comment by nathanguigui** [comment] 2020-08-27 09:15
any news for this issue ?

**Comment by mhashim6** [comment] 2020-09-07 13:07
@lotusshinoaki
maybe create a pull request please?

**Comment by lotusshinoaki** [comment] 2020-09-08 00:32
@mhashim6 
There was a problem with fixing https://github.com/lotusshinoaki/react-native-image-picker/commit/760299874f2a3075573f66ad251ab273e283fbd1
Unable to get metadata (such as MediaStore.MediaColumns.WIDTH) from URL using ContentResolver.
So I don't think this is generally a good (and well worth creating PR) solution.

**Comment by YIGENB** [comment] 2020-09-11 08:06
Check if there are other modules in your project that use the same provider. If so, please change this module AndroidManifest.xml :`      <provider
            android:name="com.imagepicker.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>`
to
`      <provider
            android:name="com.imagepicker.FileProvider"
            android:authorities="${applicationId}.PickProvider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/pick_provider_paths" />
        </provider>`
=========================
RealPathUtil.java:
`provider`
to
`PickProvider`

**Comment by aje** [comment] 2020-09-15 09:41
> # Check if there are other modules in your project that use the same provider. If so, please change this module AndroidManifest.xml :` <provider android:name="com.imagepicker.FileProvider" android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`
> to
> ` <provider android:name="com.imagepicker.FileProvider" android:authorities="${applicationId}.PickProvider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/pick_provider_paths" /> </provider>`
> RealPathUtil.java:
> `provider`
> to
> `PickProvider`

I have this module called "rn-update-apk" which requires to have a <provider> like this : 
`        <provider
                android:name="androidx.core.content.FileProvider"
                android:authorities="${applicationId}.provider"
                android:exported="false"
                android:grantUriPermissions="true">
            
            
            <meta-data tools:replace="android:resource"
                       android:name="android.support.FILE_PROVIDER_PATHS"
                       android:resource="@xml/filepaths" />
        </provider>`

I'm not able to change it.  Do you have any idea how to fix this problem?

**Comment by rafauke** [comment] 2020-09-15 14:01
> # Check if there are other modules in your project that use the same provider. If so, please change this module AndroidManifest.xml :` <provider android:name="com.imagepicker.FileProvider" android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`
> to
> ` <provider android:name="com.imagepicker.FileProvider" android:authorities="${applicationId}.PickProvider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/pick_provider_paths" /> </provider>`
> 
> RealPathUtil.java:
> `provider`
> to
> `PickProvider`

I can confirm that your solution works - I have added a PR addressing that.

**Comment by abrarqureshi** [comment] 2020-09-26 16:26
> # Check if there are other modules in your project that use the same provider. If so, please change this module AndroidManifest.xml :` <provider android:name="com.imagepicker.FileProvider" android:authorities="${applicationId}.provider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/provider_paths" /> </provider>`
> to
> ` <provider android:name="com.imagepicker.FileProvider" android:authorities="${applicationId}.PickProvider" android:exported="false" android:grantUriPermissions="true"> <meta-data android:name="android.support.FILE_PROVIDER_PATHS" android:resource="@xml/pick_provider_paths" /> </provider>`
> RealPathUtil.java:
> `provider`
> to
> `PickProvider`

Not Working!!!!!!!!!

**Comment by ardynugraha** [comment] 2020-09-28 07:18
> A possible workaround (if you don't need your pics to be public) is to use the `privateDirectory` flag:
> 
> ```js
> storageOptions={{ privateDirectory: true  }}
> ```

works in Android 10 using this flag but image file not saved in storage and choose file from gallery still not working

**Comment by iagormoraes** [comment] 2020-10-02 13:19
Follow the stack-trace

```
10-02 10:15:23.234   526   925 W System.err: java.io.IOException: Permission denied
10-02 10:15:23.234   526   925 W System.err: 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
10-02 10:15:23.234   526   925 W System.err: 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
10-02 10:15:23.234   526   925 W System.err: 	at java.io.File.createNewFile(File.java:1008)
10-02 10:15:23.234   526   925 W System.err: 	at com.imagepicker.utils.MediaUtils.createNewFile(MediaUtils.java:80)
10-02 10:15:23.234   526   925 W System.err: 	at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:274)
10-02 10:15:23.234   526   925 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-02 10:15:23.234   526   925 W System.err: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
10-02 10:15:23.234   526   925 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
10-02 10:15:23.234   526   925 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-02 10:15:23.234   526   925 W System.err: 	at android.os.Handler.handleCallback(Handler.java:883)
10-02 10:15:23.234   526   925 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-02 10:15:23.234   526   925 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
10-02 10:15:23.234   526   925 W System.err: 	at android.os.Looper.loop(Looper.java:214)
10-02 10:15:23.234   526   925 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
10-02 10:15:23.234   526   925 W System.err: 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by iagormoraes** [comment] 2020-10-02 15:41
Just did a [PR](https://github.com/react-native-image-picker/react-native-image-picker/pull/1439) with the fixes, for the moment you can add in your package.json the following:

```
"react-native-image-picker": "https://github.com/iagormoraes/react-native-image-picker",
```

**Comment by ravirajn22** [comment] 2020-10-29 12:05
If possible can you migrate to using version 3.0.0-vnext.1 https://github.com/react-native-image-picker/react-native-image-picker/releases/tag/v3.0.0-vnext.1

Check if your issue is solved.
Check 3.x.x docs for installation and API changes.

**Comment by Queeniie** [comment] 2020-11-05 15:09
Hi,
I have this problem with react-native-image-picker@2.3.4, as well as this one #1475 , both Android. (didn't try iOS yet).
My RN version is 0.63.3 and it was working well before i updated it.
I tried to update react-native-image-picker to 3.0.0 but i have the same errors.

**Comment by NeuroBanco** [comment] 2020-11-16 23:24
Hello Guys, I think this is not for everyone, but in my build.gradle file it was configured to use API 29.0.2
I just switched to API 28.0.3 - Sure with the SDK and NDK properly installed and working ...
After that I ran the Build and it worked fine on my android 10 device

**Comment by jandrell-formoso** [comment] 2020-11-27 06:52
> Hello Guys, I think this is not for everyone, but in my build.gradle file it was configured to use API 29.0.2
> I just switched to API 28.0.3 - Sure with the SDK and NDK properly installed and working ...
> After that I ran the Build and it worked fine on my android 10 device

I have the same configuration. Does it affect if the compile and targetSdkVersion is 29? or should I move back to 28?

**Comment by NeuroBanco** [comment] 2020-11-29 02:01
@jandrell-formoso I'm back to 28!

**Comment by tomsotte** [comment] 2020-12-03 13:54
Google Play Store now requires to target API 29 as you can see here https://developer.android.com/distribute/best-practices/develop/target-sdk

**Comment by LMestre14** [comment] 2021-01-12 15:43
I was using react-native-image-picker version 2.3.1 and had the error "Couldn't get file path for photo"
Installed a version from another project that was working (2.3.3) and this version works as expected

**Closed** 2021-02-10 10:55 UTC
