### ISSUE TITLE
[🐛] App Restarts when clicked photo from phone camera using react-native-image-picker

### ISSUE THREAD

**Issue by tomNjerry** [react-native-image-picker/react-native-image-picker#1547] opened 2020-12-18 05:25 UTC
### Description
- The App restarts when clicked the image using app camera using launch camera method of react-native-image-picker v3.1.1. The app is giving proper response when selected launch Image Library. The image options are 
- ``` const imagePickerOptions: ImageLibraryOptions = {
    mediaType: 'photo',
    quality: 0.5,
  }; 
- the issue occurs in both production mode as well as debug mode

### How to repeat issue and example

- step to reproduce the issue
- open the app 
- select the image from camera option 
- click the photo
- select tick button below the photo clicked 
- the app restarts

### Solution

What needs to be done to address this issue?

### Additional Information

- Image Picker version: [3.1.1]
- React Native version: [0.63.0]
- Platform: [ Android ]
- Development Operating System: [mac OS]

**Comment by tomNjerry** [comment] 2020-12-18 06:21
The issue occurs basically in MI phone i.e. my redmi 8A phone.

**Comment by sujitgawas19** [comment] 2020-12-18 06:46
Facing this issue on Motorola phones as well.

Image Picker version: [3.1.0]
React Native version: [0.61.5]
Platform: [ Android ]

**Comment by ravirajn22** [comment] 2020-12-18 08:10
Duplicate of #1502

**Closed by ravirajn22** 2020-12-18 08:10 UTC
Labels: :bug: Bug
