### ISSUE TITLE
[🐛] Property quality property not working with launchImageLibrary

### ISSUE THREAD

**Issue by tuneerclixlogix** [react-native-image-picker/react-native-image-picker#1624] opened 2021-02-22 15:01 UTC
quality property not working with launchImageLibrary

I added quality in my options
const options = {
  quality: 0.2,
  storageOptions: {
    skipBackup: true,
    path: "images",
  },
};
then i made call to launchImageLibrary(options, async (response) => {})
but still i am getting the same image size on selecting the image from library , i want the quality of image to be reduced so the filesize is less

**Comment by ravirajn22** [comment] 2021-03-18 13:46
I am unable to reproduce in latest version. What version are u using and provide more details, like the original image size and image size in the response.

**Comment by GolfredoPerezFernandez** [comment] 2021-03-20 01:21
same here

**Comment by ChrisMarlier** [comment] 2021-04-04 18:16
Same problem here. Tested on Android. If quality is the only params, their is no change on the image, which will be the same size. If I have other params like maxWidth, the quality can be changed.

**Comment by Johan-dutoit** [comment] 2021-04-29 13:18
Going to close the issue.  No information on the platform, picker version, etc.

**Closed by Johan-dutoit** 2021-04-29 13:18 UTC
Labels: :bug: Bug, :grey_question:  Need More Information
