### ISSUE TITLE
Cannot find module in jest mocking

### ISSUE THREAD

**Issue by marvin-42** [react-native-image-picker/react-native-image-picker#1485] opened 2020-11-10 14:47 UTC
Hi. When I try to mock module I've error "Cannot find module 'react-native-image-picker' from 'test/mock-react-native-image-picker.ts'".

`jest.mock("react-native-image-picker", () => ({
  showImagePicker: jest.fn(),
  launchCamera: jest.fn(),
}))`

* Image Picker version: 3.0.0-vnext.4
* React Native version: 0.63.3
* Platform: jest test
* Development Operating System: MacOS

**Comment by ravirajn22** [comment] 2020-11-10 15:07
You have to import like this

`import {launchCamera, launchImageLibrary} from 'react-native-image-picker';`

API `showImagePicker` is removed from 3.x.x versions.

**Comment by marvin-42** [comment] 2020-11-11 08:17
@ravirajn22 import in component file is working fine. The problem is only when i try to run JEST tests

**Comment by ravirajn22** [comment] 2020-11-11 08:35
I have no experience in running JEST tests but I will look into it

**Comment by nberehova** [comment] 2020-12-04 20:47
It works with appended `"main": "src/index.ts",` into `node_modules/react-native-image-picker/package.json` .
```diff
  },
+ "main": "src/index.ts",
  "types": "lib/typescript/index.d.ts",
  "version": "3.0.0-vnext.3"
}

```

Looks like for some reason jest module resolving requires this main entry point.

**Comment by ravirajn22** [comment] 2020-12-08 14:30
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

**Closed by ravirajn22** 2020-12-08 14:30 UTC

**Comment by siderakis** [comment] 2021-09-21 21:36
Adding `"main": "src/index.ts",` is still needed for non-TS projects.
