### ISSUE TITLE
Restart when Take Photo on Android 9

### ISSUE THREAD

**Issue by nahansans** [react-native-image-picker/react-native-image-picker#1503] opened 2020-11-25 02:49 UTC
i'm choose from gallery normally and can upload to API, but when i'm use take photo after take photo and click checklist the APP restart

**Comment by ravirajn22** [comment] 2020-11-25 03:30
options u use, library version and crash log

**Comment by nahansans** [comment] 2020-11-25 03:36
> options u use, library version and crash log

<manifest
  xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  package="com.crocodic.ezfitapp">

    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />

    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.CAMERA" />

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />

    <uses-feature android:name="android.hardware.camera" android:required="false" />
    <uses-feature android:name="android.hardware.camera.front" android:required="false" />
    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:usesCleartextTraffic="true"
      android:allowBackup="false"
      android:requestLegacyExternalStorage="true"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:launchMode="singleTop"
        android:screenOrientation="portrait"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
    
      <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:grantUriPermissions="true"
            android:exported="false">
            <meta-data
                tools:replace="android:resource"
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/filepaths" />
      </provider>
    </application>

</manifest>

**Comment by nahansans** [comment] 2020-11-25 03:37
> options u use, library version and crash log

react-native-image-picker version 2.3.4
no crash log

**Comment by ravirajn22** [comment] 2020-11-25 03:50
Check docs and update to version 3.x.x, 2.x.x is not supported

**Comment by nahansans** [comment] 2020-11-25 03:53
> Check docs and update to version 3.x.x, 2.x.x is not supported

link to the docs? i can't found

**Comment by deadlock** [comment] 2020-12-07 12:50
why the issue has been closed? I'm also lookin for version 3.x.x, links about the docs are broken and the version has not been release on npm.

**Comment by ravirajn22** [comment] 2020-12-07 13:18
@deadlock Upgrade to 3.x.x version. Read the docs https://github.com/react-native-image-picker/react-native-image-picker

Check latest version here https://github.com/react-native-image-picker/react-native-image-picker/releases

**Comment by deadlock** [comment] 2020-12-07 13:32
Thx @ravirajn22.

The new version continues to have the same behavior. After some time with the app on background, the first try to take a picture makes de app restart.

**Comment by ravirajn22** [comment] 2020-12-07 14:04
Its a known issue read this thread

https://github.com/react-native-image-picker/react-native-image-picker/issues/1502

The solution is not straightforward and this issue will only happen on some <2gb ram phones.

**Comment by deadlock** [comment] 2020-12-07 14:07
My phone has 4gb and the issue is happening.

I will follow the informed thread. 

Thx for the help

**Comment by ravirajn22** [comment] 2020-12-08 14:26
Duplicate of issue #1502

**Closed by ravirajn22** 2020-12-08 14:26 UTC

**Comment by rajiv-eulogik** [comment] 2022-10-11 06:24
well, I was stuck on this for long but just few minutes ago I changed the **compileSdkVersion** to **29** from 30 and it started working in **Android 11**, need to test the same in 10.
Hope this would be helpful for someone.

```
minSdkVersion = 21
compileSdkVersion = 29
targetSdkVersion = 30
```

Cheers!
