### ISSUE TITLE
[Bug]: launchImageLibrary needs cameraType to be set

### ISSUE THREAD

**Issue by alfredomarqueza** [react-native-image-picker/react-native-image-picker#1650] opened 2021-03-21 18:07 UTC
The problem is in line 29 of Options.java 

![image](https://user-images.githubusercontent.com/51949347/111915859-e08e6a80-8a3d-11eb-9fdf-01d0db462feb.png)

**Comment by Johan-dutoit** [comment] 2021-03-30 12:36
Submit a PR?

**Comment by ravirajn22** [comment] 2021-03-30 18:43
@alfredomarqueza n @Dontag unable to reproduce this issue. Could be a temporary cache issue while upgrading the library.

**Comment by ibreakthekloud** [comment] 2021-04-03 22:48
Options check for "cameraType" is causing this error: https://github.com/react-native-image-picker/react-native-image-picker/blob/710aea39e1d1e2352cbce3fc5f4aa348ebcf6c1c/android/src/main/java/com/imagepicker/Options.java#L29

**Comment by Oz-on** [comment] 2021-04-07 09:08
I had the same issue. I fixed it by setting the `cameraType` in the options.

**Comment by ravirajn22** [comment] 2021-04-07 09:12
Show your code @Oz-on. I am unable to reproduce.

**Comment by ravirajn22** [comment] 2021-04-07 14:04
I am closing until someone posts their JS code which causes the issue

**Closed by ravirajn22** 2021-04-07 14:04 UTC

**Comment by matamicen** [comment] 2021-04-22 23:44
@ravirajn22 Thanks for this Library! 

**The library fails on Android 11 Target API 30**

We were using super nice this library on:

-  version 3.0.0-vnext.4 
- Target API 29 (Android 10)
- react-native-permissions 2.2.2

**Then we migrate to:**

- Target API 30 (Becasue of Google Store DeadLines and Warnings)
- react-native-permission 3.0.2 (Last Version - Support Android 11)
- and try from  3.0.0-vnext.4 to 3.3.2

Here are the result:

From version 3.0.0-vnext.4 to 3.3.1 -> it doesn't open the library (Pixel 3 Phisical Device)
On version 3.3.2 -> Throw an error asking for **cameraType** and we just want to open the library, here is our code after asking for permissions:


 ```
const options = {
                title: 'Video Picker',
                takePhotoButtonTitle: 'Take Video...',
                mediaType: 'video',
         
              };


              launchImageLibrary(options, (response) => {
                console.log('Response = ', response);

                if (response.didCancel) {
                  console.log('User cancelled video picker');
                  this.pressVideo = false;

                } else if (response.error) {
                  console.log('ImagePicker Error: ', response.error);
                  this.pressVideo = false;
                } else if (response.customButton) {
                  console.log(
                    'User tapped custom button: ',
                    response.customButton
                  );
                } 
              });

```

And this is the Javascript error:

![WhatsApp Image 2021-04-22 at 19 18 33](https://user-images.githubusercontent.com/13036589/115797428-e57a6d00-a3a1-11eb-9a36-65cf531fdb6a.jpeg)

May be the library is trying to create a folder in an external storage and Android 11 doesn't allow to do that anymore? Just don't know ... trying to help something :)

Thanks!

Matt.

**Comment by ibreakthekloud** [comment] 2021-04-22 23:49
@matamicen see my comment above: https://github.com/react-native-image-picker/react-native-image-picker/issues/1650#issuecomment-812936191

Set the cameraType in your options, and you won't get the error.

The bug is that code assumes cameraType is set to some value and throws up while checking if it is 'front' or not when you don't set one.

**Comment by matamicen** [comment] 2021-04-23 00:04
@ibreakthekloud thanks for your answer.

it works what you say on Android 29, is not working on Android 11 Target API 30 ... 

Do you have your project on target android 30? 

Which permission are you asking before? Are you using react-native-permissions ? any help with the permission will be appreciated :) 

Thanks again!

**Comment by ravirajn22** [comment] 2021-04-23 03:13
@matamicen Since ur uprading version clearing cache and starting again the bundler should fix camera type issue. 

2. regarding targeting api 30 there is a minor change in android just check PR in the lib for the fix.

**Comment by matamicen** [comment] 2021-04-23 20:11
@ravirajn22 regarding targeting api 30, you were right (We added <query> ...  and update the android plugin also and there is no need to add the cameraType ...

Now everything is working great in both platforms and with API 30 migrated.

Thanks again for this library and help.

Matt.
