### ISSUE TITLE
ANDROID Attemt to invoke interface method

### ISSUE THREAD

**Issue by bestspyever** [react-native-image-picker/react-native-image-picker#1312] opened 2020-03-13 08:38 UTC
ANDROID Attemt to invoke interface method int com.facebook.react.bridge.ReadableArray.size() on a null object reference.

Hello, I am running in android simulator, added permissions to manifest, but it seems like Imagepicker is null.

My code is :

```
 _imagePick() {
     const options = {
  title: 'Choose image',
  customButtons: null,
  storageOptions: {
    skipBackup: true,
    path: 'images',
  },
  cancelButtonTitle: 'Cancel',
      takePhotoButtonTitle: 'Take photo',
      chooseFromLibraryButtonTitle: 'Open gallery',
};

ImagePicker.showImagePicker(options, (response) => {

  if (response.didCancel) {
    console.log('User cancelled image picker');
  } else if (response.error) {
    console.log('ImagePicker Error: ', response.error);
  } else if (response.customButton) {
    console.log('User tapped custom button: ', response.customButton);
  } else {
    const source = { uri: response.uri };

    this.setState({
      avatarSource: source,
      avatarData: response.data
    });
  }
});
  }
```

**Comment by sam1463** [comment] 2020-08-25 15:20
@bestspyever I am also running into this issue. For me, the fix is to avoid passing in `customButtons` at all, unless I'm passing in an actual array of custom buttons. If you remove `customButtons: null,` does it work for you?

This should still probably be fixed in this library. Looks like in `ButtonsHelper.java`, the `getCustomButtons` method only checks for whether the key `customButtons` exists (`if (!options.hasKey("customButtons"))`), not whether it's null, so passing in a value that's anything other than an array causes this crash. Seems like a safer way would be to also check if the value is null, and return in that case as well.

**Comment by ravirajn22** [comment] 2020-11-04 09:54
Please migrate to using version 3.x.x https://github.com/react-native-image-picker/react-native-image-picker/releases

Check 3.x.x docs for installation and API changes.
Post if you have any issue

**Comment by ravirajn22** [comment] 2020-12-12 18:48
Version 2.x.x is not longer supported, please upgrade to 3.x.x
I hope the issue is solved, if not reply here or create new issue with details I am happy to fix it.

**Closed by ravirajn22** 2020-12-12 18:48 UTC
