### ISSUE TITLE
[🐛] Application crashing on pick video from library on android 10

### ISSUE THREAD

**Issue by vitorverasm** [react-native-image-picker/react-native-image-picker#1614] opened 2021-02-10 13:24 UTC
### Description

When I try to pick a video from gallery on Android 10 the app crashes. We have a lot of closed issues reporting this like:

#1210
#1221
#1139 
#1427

## Usage

```js
static async pickVideo(
    onSuccess = (photo) => {
      reactotron.log(photo);
    },
    options = {
      mediaType: 'video'
    }
  ) {
    launchImageLibrary(options, (response) => {
      if (response.didCancel) {
        reactotron.log('User cancelled image picker');
      } else if (response.error) {
        reactotron.log('Unexpected error occurred on image picker.');
      } else if (response.customButton) {
        reactotron.log('User tapped custom button: ', response.customButton);
      } else {
        // const source = { uri: response.uri };
        // You can also display the image using data:
        // const source = {uri: `data:image/jpeg;base64,${response.data}`};
        onSuccess(response);
      }
    });
  }
```

## Stacktrace
```
2021-02-10 09:54:44.692 7739-7739/com.fortics.szchat E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fortics.szchat, PID: 7739
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/25/ORIGINAL/NONE/1712013369 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F25/ORIGINAL/NONE/1712013369} }} to activity {com.fortics.szchat/com.fortics.szchat.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.imagepicker.Utils.getVideoResponseMap(Utils.java:338)
        at com.imagepicker.ImagePickerModule.onVideoObtained(ImagePickerModule.java:138)
        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:169)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:262)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:124)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

### How to repeat issue and example

- Create new RN project
- Install latest version of ImagePicker (3.1.4)
- Run on Android 10

### Solution

This may be caused because of android 10 file handling issues, like permissions, etc.

### Additional Information

- Image Picker version: latest
- React Native version: 0.59
- Platform: Android(10)
- Development Operating System: MacOS

**Comment by ravirajn22** [comment] 2021-02-10 13:46
Check this on real device, android emulator 10 has issues I think.

**Comment by ravirajn22** [comment] 2021-02-10 16:30
@vitorverasm ?

**Comment by vitorverasm** [comment] 2021-02-10 16:37
I've tested in a real device and the picker works! But why it doesn't work on emulator, any thoughts?

**Comment by ravirajn22** [comment] 2021-02-10 16:39
From what know looks like a bug in android emulator 10 only, I can't find any more info.
Closing it for now.

**Closed by ravirajn22** 2021-02-10 16:39 UTC
Labels: :bug: Bug

**Comment by leonacky** [comment] 2021-03-07 11:01
> Check this on real device, android emulator 10 has issues I think. Confirm ones tested, post error log if it happens on real device

still get error on real device and android 8. Please check it!
`2021-03-07 17:43:10.643 7372-7372/com.zulik.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zulik.app, PID: 7372
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/1/content://media/external/images/media/91/ORIGINAL/NONE/1672579805 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F91/ORIGINAL/NONE/1672579805} }} to activity {com.zulik.app/com.zulik.MainActivity}: java.lang.NullPointerException: uri
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
        at android.app.ActivityThread.-wrap19(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: uri
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
        at android.content.ContentResolver.query(ContentResolver.java:737)
        at android.content.ContentResolver.query(ContentResolver.java:704)
        at android.content.ContentResolver.query(ContentResolver.java:662)
        at com.imagepicker.Utils.getResponseMap(Utils.java:313)
        at com.imagepicker.ImagePickerModule.onImageObtained(ImagePickerModule.java:135)
        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:166)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:7276)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
`
