### ISSUE TITLE
[🐛] launchCamera doesn't resolve

### ISSUE THREAD

**Issue by Jocodinan** [react-native-image-picker/react-native-image-picker#1977] opened 2022-04-28 17:51 UTC
### Description

Hi!, I have been using react-native-image-picker 4.4.0 for a while without problems on my app, but since I updated to 4.8.1, I have a problem with launchCamera functionality in my iOS device.

When I launch camera for first time, launchCamera response well with the image data, but then, when I launch camera again, it shows the camera, take the photo but I have no response at all and no error throw, just nothing.

```
"react-native": "0.66.4"
"react-native-image-picker": "4.8.1"
```

```
try{
      const result = await launchCamera({
        mediaType: "photo",
        quality: 0.1,
        cameraType: "back",
        includeBase64: true,
        saveToPhotos: true
      });

     console.log(result); //This only works at first time, then it never log a result
  }catch(error){
    console.log("error getting image", error);
  }
```

### How to repeat issue and example

- Just replying the above code

### Solution

- I need that launchCamera functionality always resolve a response when the user take a photo from camera on iOS

### Additional Information

- Image Picker version: 4.8.1
- React Native version: 0.66.4
- Platform: iOS only, Android Works fine
- Development Operating System: MacOS M1 Big Sur 11.3.1
- Dev tools: Xcode 13.2.1

**Comment by pgrepds** [comment] 2022-04-29 13:51
@lukebrandonfarrell I can confirm this issue, but in my case it doesn't return on the first try. I haven't noticed this since we only use the launchImageLibrary function. I have downgrade to 4.7.3 in which the changes from [#1948 ] are not integrated and the issue does not occur.  I have tested 4.8.0 as well. In short, yes this is very much likely to be caused by [#1948 ].  

A possible hotfix would be to remove the native changes from the iOS side, since the issue we wanted to fix there is very rare. The fix for android was a different issue which is described in [#1944  ] and I think we can leave this change for Android. 

I will create a new PR which rollbacks the changes on iOS, open a new issue which describes the problem the PR fixed for iOS for the launchImageLibrary (but obviously introduced this bug here for launchCamera). This is much cleaner since then we have to separate commits for two different issues. I should have done this initially. I will then look into this new problem. Does this sound good?

@Jocodinan in the meanwhile I would suggest that you downgrade to 4.8.0.

**Comment by lukebrandonfarrell** [comment] 2022-05-02 10:55
@pgrepds Thanks will be looking out for your PR and we can get it approved

**Comment by pgrepds** [comment] 2022-05-02 13:26
I have opened a [PR](https://github.com/react-native-image-picker/react-native-image-picker/pull/1978). Not a complex fix, apparently.

**Comment by lukebrandonfarrell** [comment] 2022-05-02 17:03
Fixed by https://github.com/react-native-image-picker/react-native-image-picker/pull/1978

**Closed by lukebrandonfarrell** 2022-05-02 17:03 UTC
Labels: :bug: Bug
