### ISSUE TITLE
[🐛]  URI returned from launchCamera callback incorrect

### ISSUE THREAD

**Issue by scousino** [react-native-image-picker/react-native-image-picker#1516] opened 2020-12-09 17:44 UTC
### Description

I'm calling launchCamera with the saveToPhotos option. However, in the callback I get after taking a picture the URI is still the URI pointing to the temp location. When saveToPhotos is true I expect to get the URI of the photo/video in whatever location saveToPhotos puts it.

### How to repeat issue and example
Call launchCamera with saveToPhotos set to true and provide a callback. In the callback you'll see the URI points to a temp location.

### Solution

Return the proper URI

### Additional Information

- Image Picker version: 3.0.0
- React Native version: 0.62.2
- Platform: Android
- Development Operating System: Windows
- Dev tools: Android API 29

**Comment by ravirajn22** [comment] 2020-12-09 18:45
yes thats how its written, you can upload or show image/video from temp location. Why do you want its gallery URI?

**Comment by scousino** [comment] 2020-12-09 18:51
With the temp location I can't run stat from react-native-filesystem on any of those files. But, in general having an option called saveToPhotos implies that you are only saving the photo to the public photos location, not also saving to the temp location.

Its both confusing and a space waster because now you have 2 of the same image saved on the phone in different locations. I think it should do one or the other, temp location if saveToPhotos is false, return gallery URI otherwise. Or, alternatively add another property to the response object that additionally gives the gallery URI when saveToPhotos is true.

**Comment by ravirajn22** [comment] 2020-12-09 18:58
I will try to send gallery URI when returning instead of temp, but will take some time to implement.

**Comment by maxencehenneron** [comment] 2020-12-28 10:55
This is also true when selecting a photo from the library. It returns a temp URL that cannot be used with RNFS. I want to upload the image to my server and unfortunately cannot access it...

**Comment by ravirajn22** [comment] 2021-01-21 06:10
duplicate of #1488

**Closed by ravirajn22** 2021-01-21 06:10 UTC
Labels: :bug: Bug

**Comment by betoharres** [comment] 2022-05-04 03:17
does anyone was able to get this working somehow?
