### ISSUE TITLE
image picker manager is null

### ISSUE THREAD

**Issue by eriffat896** [react-native-image-picker/react-native-image-picker#1146] opened 2019-08-05 02:19 UTC
After installing `react-native-image-picker` according to this [documentation](https://www.npmjs.com/package/react-native-image-picker) the emulator is displaying this-

```
 react-native-image-picker: NativeModule.ImagePickerManager is null. To fix this issue try these steps:
ΓÇó Run `react-native link react-native-image-picker` in the project root.
ΓÇó Rebuild and re-run the app.
ΓÇó If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
ΓÇó Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
* If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-image-picker
```

And to follow the above instruction, I try to rebuild the app but after installing the image picker app is not building. Command prompt is giving this

```
> Task :app:processDebugManifest FAILED
E:\imageTest\android\app\src\debug\AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 3s
22 actionable tasks: 1 executed, 21 up-to-date
error Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
```

And this is my ` AndroidManifest.xml` file

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.test">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
 
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:windowSoftInputMode="adjustResize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

</manifest>
```

**Comment by eriffat896** [comment] 2019-08-05 02:21
> After installing `react-native-image-picker` according to this [https://www.npmjs.com/package/react-native-image-picker](documentation) the emulator is displaying this-
> 
> ```
>  react-native-image-picker: NativeModule.ImagePickerManager is null. To fix this issue try these steps:
> ΓÇó Run `react-native link react-native-image-picker` in the project root.
> ΓÇó Rebuild and re-run the app.
> ΓÇó If you are using CocoaPods on iOS, run `pod install` in the `ios` directory and then rebuild and re-run the app. You may also need to re-open Xcode to get the new pods.
> ΓÇó Check that the library was linked correctly when you used the link command by running through the manual installation instructions in the README.
> * If you are getting this error while unit testing you need to mock the native module. Follow the guide in the README.
> If none of these fix the issue, please open an issue on the Github repository: https://github.com/react-native-community/react-native-image-picker
> ```
> 
> And to follow the above instruction, I try to rebuild the app but after installing the image picker app is not building. Command prompt is giving this
> 
> ```
> > Task :app:processDebugManifest FAILED
> E:\imageTest\android\app\src\debug\AndroidManifest.xml:22:18-91 Error:
>         Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
>         is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
>         Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.
> 
> See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
> 
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugManifest'.
> > Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
>         is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
>         Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 3s
> 22 actionable tasks: 1 executed, 21 up-to-date
> error Could not install the app on the device, read the error above for details.
> Make sure you have an Android emulator running or a device connected and have
> set up your Android development environment:
> https://facebook.github.io/react-native/docs/getting-started.html
> error Command failed: gradlew.bat app:installDebug. Run CLI with --verbose flag for more details.
> ```
> 
> And this is my ` AndroidManifest.xml` file
> 
> ```
> <manifest xmlns:android="http://schemas.android.com/apk/res/android"
>   package="com.test">
> 
>     <uses-permission android:name="android.permission.INTERNET" />
>     <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
>  
>     <uses-permission android:name="android.permission.CAMERA" />
>     <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
> 
>     <application
>       android:name=".MainApplication"
>       android:label="@string/app_name"
>       android:icon="@mipmap/ic_launcher"
>       android:roundIcon="@mipmap/ic_launcher_round"
>       android:allowBackup="false"
>       android:theme="@style/AppTheme">
>       <activity
>         android:name=".MainActivity"
>         android:label="@string/app_name"
>         android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
>         android:windowSoftInputMode="adjustResize">
>         <intent-filter>
>             <action android:name="android.intent.action.MAIN" />
>             <category android:name="android.intent.category.LAUNCHER" />
>         </intent-filter>
>       </activity>
>       <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
>     </application>
> 
> </manifest>
> ```

info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
      Memory: 538.82 MB / 3.91 GB
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

**Comment by eriffat896** [comment] 2019-08-05 02:22
info
  React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (4) x64 Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
      Memory: 538.82 MB / 3.91 GB
    Binaries:
      Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
      npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
    IDEs:
      Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245

**Comment by GonzalezRon** [comment] 2019-08-07 00:21
I am also getting the top message "react-native-image-picker: Native Module.ImagePickerManager is null." 
I manually installed the xcodeproject file to my libraries. 
And did all the previous steps but still can't get it to work.

**Comment by subashtimalsina** [comment] 2019-08-08 10:52
This NPM package had lots of problems though I have tried using it.  I encountered 
react-native-image-picker: NativeModule.ImagePickerManager is null. To fix this issue try these steps:
ΓÇó Run `react-native link react-native-image-picker` in the project root.
most of the time.

**Comment by oliverkuchies** [comment] 2019-08-09 23:36
Having same issue using expo.

**Comment by subashtimalsina** [comment] 2019-08-12 03:51
Thank you for your email, I want to use this NPM module on my android as
well as ios application but i encounter an error, Which is frequent and
iterative.
So, It blocks me to debug my application on my device as well as Emmulator.
So, what are the viable solution for me so that, I can implement it on my
project. Hope your response will cover all of my concerns.

Thank you!

**Comment by rogger-frogger** [comment] 2019-08-23 07:41
I fixed it by running 'pod install', for RN >= 60

**Comment by alebupal** [comment] 2019-09-05 09:48
I have the same problem when running the application on Android (react-native-image-picker: Native Module.ImagePickerManager is null).
I have all versions of the manual.
I have tried to link react-native-image-picker manually and automatically.

Is there any solution?

**Comment by yl-flyer** [comment] 2019-09-28 20:00
Same problem? any solutions?

**Comment by larryTheGeek** [comment] 2019-10-02 09:05
I also have the same problem while using expo I have tried running `react-native link react-native-image-picker` did not work for me. This is what worked for me.
1. Unistall the latest version
 `npm uninstall react-native-image-picker`
2. Installed version 0.28.0
  `npm install react-native-image-picker@0.28.0 --save`
   `react-native link react-native-image-picker`

**Comment by subashtimalsina** [comment] 2019-10-02 11:20
Thanks React-Native-Community/React-Native-Image-Picker, i had solved this
problem already i am not using expo for react native development.

**Comment by fahadhaq** [comment] 2019-10-07 07:21
@subashtimalsina how did you solve the issue? I am getting the same error

**Comment by fahadhaq** [comment] 2019-10-07 07:24
Dont worry It seems the Linking didnt work. I manually went through the manual linking to solve the issue.

**Comment by subashtimalsina** [comment] 2019-10-09 15:27
I am done with this issue.

**Comment by MuhammadRaheelFayyaz** [comment] 2019-10-28 12:40
I also have the same problem
. This is what worked for me.

Unistall the latest version
npm uninstall react-native-image-picker
Installed version 0.28.0
npm install react-native-image-picker@0.28.0 --save
react-native link react-native-image-picker

**Comment by joinintern** [comment] 2019-11-04 10:14
This solution really solve my problem .

follow this steps.

Unistall the latest version
npm uninstall react-native-image-picker
Installed version 0.28.0
npm install react-native-image-picker@0.28.0 --save
react-native link react-native-image-picker

**Comment by cicomint** [comment] 2019-11-05 05:20
is this issue still happened?

**Comment by NoonBenbraik** [comment] 2019-11-05 13:14
> is this issue still happened?

YES!

**Comment by MeisterTea** [comment] 2019-11-20 10:57
still happening with latest release

**Comment by vnctmdc** [comment] 2019-11-22 03:33
What can I do? What can I do?

**Comment by fahadhaq** [comment] 2019-11-22 04:09
This should be fixed in the latest version. Please grab the lastest one released like 4 days ago which has the code for Android to read images from local resources. I have it working now.

**Comment by FrenchMajesty** [comment] 2019-12-20 15:12
Checking in. Still happening as of mid December 2019

**Comment by pedromelo98** [comment] 2020-01-21 17:41
Still happening

**Comment by Johan-dutoit** [comment] 2020-01-22 07:32
Can any of you provide a reproducible example?
My guess is you're missing a step in the installation.

**Comment by rafaelcavalcante** [comment] 2020-02-03 12:05
> Can any of you provide a reproducible example?
> My guess is you're missing a step in the installation.

It's working for my while developing, but i'm getting this error message when i try to run tests

**Comment by lfalkner** [comment] 2020-02-14 16:37
I'm using 1.1.x for react-native-image picker, and react-native 59.9. I was able to get around this error in tests by mocking the native module. In my Jest setup script, I included this, and the tests passed:

```jest.mock('react-native-image-picker', () => ({
}));```

**Comment by Anujmoglix** [comment] 2020-04-07 19:35
I am still facing issue.

**Comment by KingJics** [comment] 2020-04-09 20:37
Hello Please I'm facing the same problem
//Package.json file
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
"dependencies": {
    "@expo/vector-icons": "^10.0.6",
    "@react-native-community/masked-view": "^0.1.5",
    "@react-navigation/bottom-tabs": "^5.2.4",
    "@react-navigation/drawer": "^5.3.3",
    "@react-navigation/material-top-tabs": "^5.1.6",
    "@react-navigation/native": "^5.1.3",
    "@react-navigation/stack": "^5.2.6",
    "@react-navigation/tabs": "0.0.0-alpha.12",
    "axios": "^0.19.2",
    "expo": "~36.0.0",
    "expo-asset": "^8.0.0",
    "expo-font": "^8.0.0",
    "expo-image-picker": "~8.0.1",
    "expo-linear-gradient": "^8.0.0",
    "expo-ui-kit": "^0.1.0",
    "formik": "^2.1.4",
    "indicative": "^7.4.4",
    "native": "^0.3.3",
    "native-base": "^2.13.8",
    "paper": "^0.12.4",
    "prop-types": "^15.7.2",
    "react": "^16.13.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-app-intro-slider": "^3.0.0",
    "react-native-elements": "^1.2.7",
    "react-native-formik": "^1.7.8",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-image-picker": "^0.28.0",
    "react-native-textinput-effects": "^0.5.1",
    "react-native-web": "~0.11.7",
    "react-navigation": "^4.3.3",
    "react-navigation-drawer": "^2.4.7",
    "react-navigation-stack": "^2.3.6",
    "styled-components": "^5.0.1",
    "yup": "^0.28.3"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "babel-preset-expo": "~8.0.0"
  },
  "private": true
}

**Comment by Anujmoglix** [comment] 2020-04-10 08:22
Try to clean build once @KingJics

**Comment by ashton-hoss** [comment] 2020-05-07 18:10
I have the exact issue and I use expo. What's the fix?

**Comment by juliasliu** [comment] 2020-06-03 05:20
I am still experiencing this issue and I tried downgrading the version of the dependency as well. It works normally in the iOS simulator when I run `yarn ios`, but it errors in the Expo Client app on my iOS device.

Does this error also occur during app deployment?

**Comment by c0deNameEmmanuelNsanga** [comment] 2020-06-04 08:41
same issue guys...any solution please?

**Comment by kwoktung** [comment] 2020-06-22 10:04
i have some problem; react native version  0.62

then i use `npx react-native init AwesomeTSProject --template react-native-template-typescript` to init a new Project

then copy file(expect android and ios) to to new project.

it work.

**Comment by jldaii** [comment] 2020-07-18 12:25
> 我有一些问题；反应本地版本0.62
> 
> 然后我`npx react-native init AwesomeTSProject --template react-native-template-typescript`用来启动一个新项目
> 
> 然后将所有文件（android和ios除外）复制到新项目。
> 
> 这行得通。



> i have some problem; react native version 0.62
> 
> then i use `npx react-native init AwesomeTSProject --template react-native-template-typescript` to init a new Project
> 
> then copy all files(except android and ios) to to new project.
> 
> it work.

Yes, it is feasible. But why?

**Comment by jldaii** [comment] 2020-07-18 13:13
> i have some problem; react native version 0.62
> 
> then i use `npx react-native init AwesomeTSProject --template react-native-template-typescript` to init a new Project
> 
> then copy all files(except android and ios) to to new project.
> 
> it work.

Yes, it is feasible. But why?

**Comment by nikhataara** [comment] 2020-07-28 09:31
Please, can anyone help me out with this error?
facing this issue from so long

**Comment by KhalidBhyan** [comment] 2020-08-11 19:08
any solution for this problem?
```
"react-native": "0.62.2"
"react-native-image-picker": "^2.3.3
```

**Comment by bimbox-open** [comment] 2020-08-12 02:59
Today I face the same problem when I integrate this package. But I try in other way! My RN version is 0.61.5,  this package version is 2.3.3.  I have solved this problem!  
follow this step below :
1. yarn add react-native-image-picker
2.manually add  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'  to 'target 'xxxApp' do'
3.if react-native link react-native-image-picker,  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'  locate in 'target 'xxxApp-tvOSTests' do' ,this result in error above.

![Snip20200812_2](https://user-images.githubusercontent.com/51961838/89969922-2c985600-dc8a-11ea-8a06-64d404f5a261.png)

**Comment by nikhataara** [comment] 2020-08-12 05:14
It is because if we use expo for react native image picker

If you are using expo use import expo image picker 
If you are using react native use import react native image picker

**Comment by KhalidBhyan** [comment] 2020-08-12 05:39
@bimbox-open thank you for your help, but `pod install` leads to another error, I think it's applicable only in macOS, I'm using ubuntu at the moment
I did `gem install pod` before that and when running `pod install` it shows some progress and installs a lot of stuff but it shows this error:
```
[!] /bin/bash -c 
set -e
#!/bin/bash
# Copyright (c) Facebook, Inc. and its affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

set -e

PLATFORM_NAME="${PLATFORM_NAME:-iphoneos}"
CURRENT_ARCH="${CURRENT_ARCH}"

if [ -z "$CURRENT_ARCH" ] || [ "$CURRENT_ARCH" == "undefined_arch" ]; then
    # Xcode 10 beta sets CURRENT_ARCH to "undefined_arch", this leads to incorrect linker arg.
    # it's better to rely on platform name as fallback because architecture differs between simulator and device

    if [[ "$PLATFORM_NAME" == *"simulator"* ]]; then
        CURRENT_ARCH="x86_64"
    else
        CURRENT_ARCH="armv7"
    fi
fi

export CC="$(xcrun -find -sdk $PLATFORM_NAME cc) -arch $CURRENT_ARCH -isysroot $(xcrun -sdk $PLATFORM_NAME --show-sdk-path)"
export CXX="$CC"

# Remove automake symlink if it exists
if [ -h "test-driver" ]; then
    rm test-driver
fi

./configure --host arm-apple-darwin

# Fix build for tvOS
cat << EOF >> src/config.h
/* Add in so we have Apple Target Conditionals */
#ifdef __APPLE__
#include <TargetConditionals.h>
#include <Availability.h>
#endif
/* Special configuration for AppleTVOS */
#if TARGET_OS_TV
#undef HAVE_SYSCALL_H
#undef HAVE_SYS_SYSCALL_H
#undef OS_MACOSX
#endif
/* Special configuration for ucontext */
#undef HAVE_UCONTEXT_H
#undef PC_FROM_UCONTEXT
#if defined(__x86_64__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__rip
#elif defined(__i386__)
#define PC_FROM_UCONTEXT uc_mcontext->__ss.__eip
#endif
EOF

# Prepare exported header include
EXPORTED_INCLUDE_DIR="exported/glog"
mkdir -p exported/glog
cp -f src/glog/log_severity.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/raw_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/stl_logging.h "$EXPORTED_INCLUDE_DIR/"
cp -f src/glog/vlog_is_on.h "$EXPORTED_INCLUDE_DIR/"

checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for arm-apple-darwin-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for arm-apple-darwin-gcc...  -arch armv7 -isysroot 
checking whether the C compiler works... no
/bin/bash: line 24: xcrun: command not found
/bin/bash: line 24: xcrun: command not found
/home/khalid/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing: Unknown `--is-lightweight' option
Try `/home/khalid/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
configure: error: in `/home/khalid/Library/Caches/CocoaPods/Pods/Release/Flipper-Glog/0.3.6-1dfd6':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

by the way thank you man, I think like @nikhataara said because we use expo we should use something expo for image picking

**Comment by Saidfatah** [comment] 2020-08-29 19:40
I fixed finally 
2-uninstalled the package 
2 unlinked it 
3 install again 
4- (the most important ) is you need permission obviously , so I added these to  AndroidManifest.xml in android/app/src/main  :
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

**Comment by KawaljeetSBagga** [comment] 2020-09-18 11:17
For those using Jest, you will need to mock this library. To do so, simply create a new File called _'react-native-image-picker'_ under __test_ folder. And add following lines of code inside it:


```
import {NativeModules} from 'react-native';

// Mock the ImagePickerManager native module to allow us to unit test the JavaScript code
NativeModules.ImagePickerManager = {
  showImagePicker: jest.fn(),
  launchCamera: jest.fn(),
  launchImageLibrary: jest.fn(),
};

// Reset the mocks before each test
global.beforeEach(() => {
  jest.resetAllMocks();
});

```

This worked for me. Thanks

**Comment by PaulPourtout** [comment] 2020-11-02 10:36
> I also have the same problem while using expo I have tried running `react-native link react-native-image-picker` did not work for me. This is what worked for me.
> 
>     1. Unistall the latest version
>        `npm uninstall react-native-image-picker`
> 
>     2. Installed version 0.28.0
>        `npm install react-native-image-picker@0.28.0 --save`
>        `react-native link react-native-image-picker`

I had the same problem after an upgrade from RN0.059 to 0.63 and version 0.28 of the lib did work for me on iOS but on android as the version is not on androidX it failed. Installing version 
1.1.0 of RN-image-picker worked on both ios and android. So thank you very much for giving the idea of downgrading the lib.

In conclusion :  `yarn add react-native-image-picker@1.1.0`  resolved it for me

**Comment by ravirajn22** [comment] 2020-12-08 14:35
I hope the issue is solved, if not create new issue with details I am happy to fix it. This thread is long and tries to mingle lot of issues together.

Version 2.x.x is not longer supported, please upgrade to 3.x.x

**Closed by ravirajn22** 2020-12-08 14:35 UTC

**Comment by AlishaSoedamah** [comment] 2022-11-24 19:24
> I also have the same problem while using expo I have tried running `react-native link react-native-image-picker` did not work for me. This is what worked for me.
> 
> 1. Unistall the latest version
>    `npm uninstall react-native-image-picker`
> 2. Installed version 0.28.0
>    `npm install react-native-image-picker@0.28.0 --save`
>    `react-native link react-native-image-picker`

Thanks, this 'still' worked like a charm!
