### ISSUE TITLE
App restarts when we open the camera or gallery to get photos.

### ISSUE THREAD

**Issue by pruthvirajkarur** [react-native-image-picker/react-native-image-picker#1460] opened 2020-11-01 04:53 UTC
App restarts when we try to take photo from camera or gallery. I tried to debug the issue or see the logs.
Debug also goes off when we open the camera. so the issue is not after we take the photo but before taking the photo itself. As soon as we open the camera the app would have already lost or destroyed.
**Below are the versions used**
    **"react-native": "0.62.2",**
    **"react-native-image-picker": "^2.3.3",**
**Android version 9**
**Device name : Mi a1**

and it does not happen every time. If we try for multiple times it works for 2 or 3rd attempt and then starts working.
In the first 2 attempts it will restart for sure.

I have tried all the solutions which are available.

**Comment by scrapecoder** [comment] 2020-11-09 09:25
facing same..Any updates?

**Comment by Johan-dutoit** [comment] 2020-11-09 09:26
Sounds like permission issue.  Have you migrating to vnext?

**Comment by ekzotech** [comment] 2020-11-10 10:33
I have same issue. Faced it when upgraded to latest RN 0.63.3 and latest react-native-image-picker. No issues with permissions, I'll manually checking if app has no permissions to camera/gallery and retrieving it before access to camera/gallery

**Comment by AnurajDev** [comment] 2020-11-16 06:21
Same issue while upgrading React Native to "0.63.3"
react-native-image-picker: "2.3.4"

**Comment by CastixGitHub** [comment] 2020-11-18 14:30
@ekzotech can you check if it is a duplicate of #1499 ? or provide a different logcat of the crash?

**Comment by ekzotech** [comment] 2020-11-18 23:07
> @ekzotech can you check if it is a duplicate of #1499 ? or provide a different logcat of the crash?

I don't know really.
If I'm trying to access to an image from gallery - app restarts. Before showing gallery app asked me about permissions. I gave those permissions.
After tapping on a picture - app just restarts.
All I have in logcat about this is:
`2020-11-19 04:02:34.064 29580-29637/com.camera E/Perf: Fail to get file list com.camera
2020-11-19 04:02:34.064 29580-29637/com.camera E/Perf: getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array`

But on access to picture from the camera logcat gave me EACCESS error.

**Comment by cristea2017** [comment] 2020-12-07 10:44
is this specific for only xiaomi device's ? :D same for me `xiaomi redmi note 5`

**Comment by livnunes** [comment] 2020-12-10 09:30
Also having this issue, not specific to xiaomi devices, also tried on a Samsung and the same thing happens.

**Comment by efstathiosntonas** [comment] 2020-12-21 08:07
I have some users on Samsung devices on production complaining about this, unfortunately I do not own a Samsung device to retrieve logcat.

**Comment by HappyCodingLover** [comment] 2020-12-23 12:56
I have this issue on xiaomi, too
On Samsung, it works.
```
"react-native": "0.62.2",
"react-native-image-picker": "^2.3.4",
```

**Comment by sanguineti** [comment] 2021-01-08 06:56
Same issue here. Huawei device running Android 10. In iOS all works fine.

```
"react-native": "0.63.3"
"react-native-image-picker": "^3.1.3"
```

**Comment by novonimo** [comment] 2021-01-09 16:38
> App restarts when we try to take photo from camera or gallery. I tried to debug the issue or see the logs.
> Debug also goes off when we open the camera. so the issue is not after we take the photo but before taking the photo itself. As soon as we open the camera the app would have already lost or destroyed.
> **Below are the versions used**
> **"react-native": "0.62.2",**
> **"react-native-image-picker": "^2.3.3",**
> **Android version 9**
> **Device name : Mi a1**
> 
> and it does not happen every time. If we try for multiple times it works for 2 or 3rd attempt and then starts working.
> In the first 2 attempts it will restart for sure.
> 
> I have tried all the solutions which are available.

can you post your code? 
are you use the "options" object and "callback" options?

**Comment by ravirajn22** [comment] 2021-01-21 05:40
duplicate of #1502

**Closed by ravirajn22** 2021-01-21 05:40 UTC
